import React from "react";

const ProductPDFLayout = ({ products, logoUrl, companyName }) => {
  return (
    <div
      style={{
        padding: "20px",
        fontFamily: "Arial, sans-serif",
        backgroundColor: "#fff",
        color: "#000",
      }}
    >
      {/* Header */}
      <div style={{ display: "flex", alignItems: "center", marginBottom: "20px" }}>
        {logoUrl && <img src={logoUrl} alt="Logo" style={{ width: 100, marginRight: 20 }} />}
        <h2 style={{ margin: 0 }}>{companyName || "My Company"}</h2>
      </div>

      <h3 style={{ textAlign: "center", marginBottom: "20px" }}>Products Report</h3>

      <table style={{ width: "100%", borderCollapse: "collapse" }}>
        <thead>
          <tr>
            <th style={{ border: "1px solid #000", padding: "8px" }}>ID</th>
            <th style={{ border: "1px solid #000", padding: "8px" }}>Image</th>
            <th style={{ border: "1px solid #000", padding: "8px" }}>Name</th>
            <th style={{ border: "1px solid #000", padding: "8px" }}>Category</th>
            <th style={{ border: "1px solid #000", padding: "8px" }}>Brand</th>
            <th style={{ border: "1px solid #000", padding: "8px" }}>Price</th>
            <th style={{ border: "1px solid #000", padding: "8px" }}>Stock</th>
            <th style={{ border: "1px solid #000", padding: "8px" }}>Key Features</th>
          </tr>
        </thead>
        <tbody>
          {products.map((p) => (
            <tr key={p.id}>
              <td style={{ border: "1px solid #000", padding: "8px" }}>{p.id}</td>
              <td style={{ border: "1px solid #000", padding: "8px", textAlign: "center" }}>
                {p.image_urls && p.image_urls[0] && (
                  <img
                    src={p.image_urls[0]}
                    alt={p.name}
                    style={{ width: 50, height: 50, objectFit: "cover" }}
                  />
                )}
              </td>
              <td style={{ border: "1px solid #000", padding: "8px" }}>{p.name}</td>
              <td style={{ border: "1px solid #000", padding: "8px" }}>{p.category_name}</td>
              <td style={{ border: "1px solid #000", padding: "8px" }}>{p.brand_name}</td>
              <td style={{ border: "1px solid #000", padding: "8px" }}>${p.price}</td>
              <td style={{ border: "1px solid #000", padding: "8px" }}>{p.stock}</td>
              <td style={{ border: "1px solid #000", padding: "8px" }}>
                {Array.isArray(p.key_features) ? p.key_features.join(", ") : "-"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ marginTop: "20px", textAlign: "center", fontSize: 12 }}>
        Generated by {companyName || "Company Dashboard"}
      </div>
    </div>
  );
};

export default ProductPDFLayout;
