// import commercial from "../../../assets/images/commercial.webp"
// import electrical1 from "../../../assets/images/electrical1.webp"

// import hvac1 from "../../../assets/images/hvac1.webp"
// // import hvac2 from "../../../assets/images/hvac2.jpg"
// // import hvac3 from "../../../assets/images/hvac3.jpg"
// // import epoxy1 from "../../../assets/images/epoxy1.jpg"
// // import epoxy2 from "../../../assets/images/epoxy2.jpg"
// // import epoxy3 from "../../../assets/images/epoxy3.jpg"


// export const ALL_PROJECTS = [
//   // Your existing 3 projects here...
  
//   {
//     id: 4,
//     name: "Retail Store Fit-Out",
//     category: "Retail Fit-Out",
//     client: "Al Nahdi Pharmacies",
//     year: 2023,
//     duration: "4 months",
//     budget: "SAR 350,000",
//     featured: false,
//     teamSize: 6,
//     image: commercial,
//     images: [
//       commercial,
//       commercial,
//       commercial,
//       commercial,
//       commercial,
//     ],
//     description: "Modern retail store interiors with optimized product displays and customer flow.",
//     challengeSolution: [
//       {
//         title: "Challenge",
//         content: "Store layout was inefficient and lacked brand consistency.",
//         icon: "⚡",
//         iconBgColor: "bg-orange-100",
//         iconTextColor: "text-orange-500",
//       },
//       {
//         title: "Solution",
//         content: "Redesigned floor plan, added branded displays, and improved lighting.",
//         icon: "💡",
//         iconBgColor: "bg-blue-100",
//         iconTextColor: "text-blue-500",
//       },
//     ],
//     testimonial: {
//       quote: "The new store layout increased customer engagement and sales.",
//       name: "Sara Al-Mansour",
//       title: "Retail Manager",
//       company: "Al Nahdi Pharmacies",
//       rating: 5,
//     },
//     investment: {
//       price: "350,000",
//       currency: "SAR",
//       features: [
//         "Custom shelving & displays",
//         "Lighting design",
//         "Branding & signage",
//         "Project management",
//         "After-sales support",
//       ],
//       ctaText: "Request Quote",
//     },
//   },
//   {
//     id: 5,
//     name: "Healthcare Clinic Interior",
//     category: "Healthcare",
//     client: "Saudi Medical Center",
//     year: 2022,
//     duration: "7 months",
//     budget: "SAR 750,000",
//     featured: true,
//     teamSize: 15,
//     image: hvac1,
//     images: [
//       hvac1,
//       hvac1,
//       hvac1,
//       hvac1,
//       hvac1,
//       "https://placehold.co/800x600/006400/ffffff?text=Clinic+2",
//     ],
//     description: "Functional and welcoming clinic interiors designed to enhance patient comfort.",
//     challengeSolution: [
//       {
//         title: "Challenge",
//         content: "Existing layout caused long patient wait times and inefficient staff workflow.",
//         icon: "⚡",
//         iconBgColor: "bg-orange-100",
//         iconTextColor: "text-orange-500",
//       },
//       {
//         title: "Solution",
//         content: "Optimized layout for workflow efficiency and added soothing aesthetics for patients.",
//         icon: "💡",
//         iconBgColor: "bg-blue-100",
//         iconTextColor: "text-blue-500",
//       },
//     ],
//     testimonial: {
//       quote: "Patients and staff love the new environment – functional and calming.",
//       name: "Dr. Fahad Al-Zahrani",
//       title: "Clinic Director",
//       company: "Saudi Medical Center",
//       rating: 5,
//     },
//     investment: {
//       price: "750,000",
//       currency: "SAR",
//       features: [
//         "Medical-grade materials",
//         "Optimized workflow design",
//         "Lighting & ventilation",
//         "Project management",
//         "Maintenance plan",
//       ],
//       ctaText: "Get Quote",
//     },
//   },
//   {
//     id: 6,
//     name: "Industrial Warehouse Layout",
//     category: "Industrial",
//     client: "Al Jazeera Logistics",
//     year: 2023,
//     duration: "5 months",
//     budget: "SAR 900,000",
//     featured: false,
//     teamSize: 12,
//     image: electrical1,
//     images: [
//       electrical1,
//       electrical1,
//       electrical1,
//       electrical1,
//       "https://placehold.co/800x600/2F4F4F/ffffff?text=Warehouse+2",
//     ],
//     description: "Warehouse redesign with optimized storage systems and streamlined logistics.",
//     challengeSolution: [
//       {
//         title: "Challenge",
//         content: "Poorly organized storage reduced operational efficiency.",
//         icon: "⚡",
//         iconBgColor: "bg-orange-100",
//         iconTextColor: "text-orange-500",
//       },
//       {
//         title: "Solution",
//         content: "Introduced modular storage racks and clear workflow zones.",
//         icon: "💡",
//         iconBgColor: "bg-blue-100",
//         iconTextColor: "text-blue-500",
//       },
//     ],
//     testimonial: {
//       quote: "Our operations are now much faster and safer with the new layout.",
//       name: "Mohammed Al-Harbi",
//       title: "Operations Manager",
//       company: "Al Jazeera Logistics",
//       rating: 4.5,
//     },
//     investment: {
//       price: "900,000",
//       currency: "SAR",
//       features: [
//         "Storage optimization",
//         "Safety upgrades",
//         "Workflow redesign",
//         "Project management",
//       ],
//       ctaText: "Request Quote",
//     },
//   },
//   {
//     id: 7,
//     name: "Restaurant & Hospitality Design",
//     category: "Restaurant & Hospitality",
//     client: "The Olive Branch",
//     year: 2024,
//     duration: "6 months",
//     budget: "SAR 550,000",
//     featured: true,
//     teamSize: 10,
//     image: "https://placehold.co/800x600/800080/ffffff?text=Restaurant",
//     images: [
//       "https://placehold.co/800x600/800080/ffffff?text=Restaurant+1",
//       "https://placehold.co/800x600/9370DB/ffffff?text=Restaurant+2",
//     ],
//     description: "Elegant restaurant design blending modern aesthetics with cozy ambiance.",
//     challengeSolution: [
//       {
//         title: "Challenge",
//         content: "Limited space and need for a unique dining experience.",
//         icon: "⚡",
//         iconBgColor: "bg-orange-100",
//         iconTextColor: "text-orange-500",
//       },
//       {
//         title: "Solution",
//         content: "Optimized layout with intimate seating zones and aesthetic lighting.",
//         icon: "💡",
//         iconBgColor: "bg-blue-100",
//         iconTextColor: "text-blue-500",
//       },
//     ],
//     testimonial: {
//       quote: "Customers love the ambiance, and the design is very Instagrammable!",
//       name: "Layla Al-Farhan",
//       title: "Owner",
//       company: "The Olive Branch",
//       rating: 5,
//     },
//     investment: {
//       price: "550,000",
//       currency: "SAR",
//       features: [
//         "Interior design",
//         "Furniture & lighting",
//         "Branding & signage",
//         "Project management",
//         "Aftercare support",
//       ],
//       ctaText: "Request Quote",
//     },
//   },
//   {
//     id: 8,
//     name: "Luxury Penthouse Interiors",
//     category: "Residential",
//     client: "Nasser Al-Dossary",
//     year: 2024,
//     duration: "7 months",
//     budget: "SAR 1,000,000",
//     featured: false,
//     teamSize: 12,
//     image: "https://placehold.co/800x600/191970/ffffff?text=Penthouse",
//     images: [
//       "https://placehold.co/800x600/191970/ffffff?text=Penthouse+1",
//       "https://placehold.co/800x600/000080/ffffff?text=Penthouse+2",
//     ],
//     description: "High-end penthouse interiors with panoramic city views and premium finishes.",
//     challengeSolution: [
//       {
//         title: "Challenge",
//         content: "Integrating luxury finishes while maintaining functional spaces.",
//         icon: "⚡",
//         iconBgColor: "bg-orange-100",
//         iconTextColor: "text-orange-500",
//       },
//       {
//         title: "Solution",
//         content: "Custom furniture and thoughtful spatial planning.",
//         icon: "💡",
//         iconBgColor: "bg-blue-100",
//         iconTextColor: "text-blue-500",
//       },
//     ],
//     testimonial: {
//       quote: "The design is breathtaking and perfectly matches our expectations.",
//       name: "Nasser Al-Dossary",
//       title: "Homeowner",
//       company: "Private Residence",
//       rating: 5,
//     },
//     investment: {
//       price: "1,000,000",
//       currency: "SAR",
//       features: [
//         "Luxury interiors",
//         "Custom furniture",
//         "Lighting design",
//         "Project management",
//         "Aftercare support",
//       ],
//       ctaText: "Request Quote",
//     },
//   },
//   {
//     id: 9,
//     name: "Modern Cafe Interiors",
//     category: "Restaurant & Hospitality",
//     client: "Bean & Brew",
//     year: 2023,
//     duration: "3 months",
//     budget: "SAR 200,000",
//     featured: false,
//     teamSize: 5,
//     image: "https://placehold.co/800x600/FF4500/ffffff?text=Cafe",
//     images: [
//       "https://placehold.co/800x600/FF6347/ffffff?text=Cafe+1",
//       "https://placehold.co/800x600/FF7F50/ffffff?text=Cafe+2",
//     ],
//     description: "Trendy cafe interiors designed for comfort and social media appeal.",
//     challengeSolution: [
//       {
//         title: "Challenge",
//         content: "Small space requiring creative seating and flow design.",
//         icon: "⚡",
//         iconBgColor: "bg-orange-100",
//         iconTextColor: "text-orange-500",
//       },
//       {
//         title: "Solution",
//         content: "Compact seating, optimized layout, and cozy lighting elements.",
//         icon: "💡",
//         iconBgColor: "bg-blue-100",
//         iconTextColor: "text-blue-500",
//       },
//     ],
//     testimonial: {
//       quote: "The cafe is cozy and stylish – customers love it!",
//       name: "Faisal Al-Khalid",
//       title: "Owner",
//       company: "Bean & Brew",
//       rating: 4.5,
//     },
//     investment: {
//       price: "200,000",
//       currency: "SAR",
//       features: [
//         "Interior design",
//         "Furniture & lighting",
//         "Branding & signage",
//         "Project management",
//       ],
//       ctaText: "Get Quote",
//     },
//   },
//   {
//     id: 10,
//     name: "Corporate Headquarters",
//     category: "CommercialOffices",
//     client: "Saudi Tech Solutions",
//     year: 2024,
//     duration: "9 months",
//     budget: "SAR 2,500,000",
//     featured: true,
//     teamSize: 30,
//     image: "https://placehold.co/800x600/2E8B57/ffffff?text=Corporate+HQ",
//     images: [
//       "https://placehold.co/800x600/2E8B57/ffffff?text=HQ+1",
//       "https://placehold.co/800x600/3CB371/ffffff?text=HQ+2",
//     ],
//     description: "State-of-the-art corporate headquarters with collaborative spaces and modern interiors.",
//     challengeSolution: [
//       {
//         title: "Challenge",
//         content: "Designing a functional space for a large workforce while maintaining aesthetics.",
//         icon: "⚡",
//         iconBgColor: "bg-orange-100",
//         iconTextColor: "text-orange-500",
//       },
//       {
//         title: "Solution",
//         content: "Flexible workspaces, meeting rooms, and premium finishes throughout.",
//         icon: "💡",
//         iconBgColor: "bg-blue-100",
//         iconTextColor: "text-blue-500",
//       },
//     ],
//     testimonial: {
//       quote: "Our employees love the new HQ – functional and inspiring.",
//       name: "Khalid Al-Mutairi",
//       title: "CEO",
//       company: "Saudi Tech Solutions",
//       rating: 5,
//     },
//     investment: {
//       price: "2,500,000",
//       currency: "SAR",
//       features: [
//         "Workspace planning",
//         "Meeting rooms & lounges",
//         "Lighting & tech integration",
//         "Project management",
//         "Aftercare support",
//       ],
//       ctaText: "Get Quote",
//     },
//   },
// ];
